# 生产环境配置文件
server:
  port: 8288
  servlet:
    context-path: /ForeSee

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://222.200.184.74:8888/eureka/


http:
  REST_URL_PREFIX: http://222.200.184.74:6666